services:
  - type: web
    name: ecommerce-project
    runtime: static
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BASE_PATH
        value: /
